import type { Metadata } from "next";
import "../globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/charts/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import NavigationBar from "@/components/NavigationBar";

export const metadata: Metadata = {
  title: "Feedback Flow",
  description: "Generated by create next app",
};

export default function BaseLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className={" h-dvh w-dvw overflow-hidden bg-bone px-7 pb-4 pt-10"}>
      <MantineProvider>
        <NavigationBar />
        {children}
      </MantineProvider>
    </body>
  );
}
