import { Emotion } from "@/types";

export const rulerEmotionsMatrix: Emotion[][] = [
  [
    {
      name: "Enraged",
      pleasantness: -6,
      energy: 6,
      description: "made furious by something; filled with extreme anger",
      id: 1,
    },
    {
      name: "Terrified",
      pleasantness: -5,
      energy: 6,
      description: "consumed by fear",
      id: 2,
    },
    {
      name: "Panicked",
      pleasantness: -4,
      energy: 6,
      description: "feeling frantic and overcome by fear",
      id: 3,
    },
    {
      name: "Shocked",
      pleasantness: -3,
      energy: 6,
      description: "experiencing extreme horrir, disgust, and surprise",
      id: 4,
    },
    {
      name: "Impassioned",
      pleasantness: -2,
      energy: 6,
      description: "filled with lots of emotion",
      id: 5,
    },
    {
      name: "Hyper",
      pleasantness: -1,
      energy: 6,
      description: "feeling energetic and like you want to move around",
      id: 6,
    },
    {
      name: "Surprised",
      pleasantness: 1,
      energy: 6,
      description: "caught off guard by something unexpected or unusual",
      id: 7,
    },
    {
      name: "Awe",
      pleasantness: 2,
      energy: 6,
      description: "feeling like you are in presence of something vast",
      id: 8,
    },
    {
      name: "Exhilirated",
      pleasantness: 3,
      energy: 6,
      description: "in high spirits; cheerful and envigorated",
      id: 9,
    },
    {
      name: "Thrilled",
      pleasantness: 4,
      energy: 6,
      description: "feeling very excited all of a sudden",
      id: 10,
    },
    {
      name: "Elated",
      pleasantness: 5,
      energy: 6,
      description: "very joyful, proud, or enthusiastic",
      id: 11,
    },
    {
      name: "Ecstatic",
      pleasantness: 6,
      energy: 6,
      description: "feeling intense joy or happiness",
      id: 12,
    },
  ],
  [
    {
      name: "Livid",
      pleasantness: -6,
      energy: 5,
      description: "feeling furious about something or someone",
      id: 13,
    },
    {
      name: "Irate",
      pleasantness: -5,
      energy: 5,
      description: "feeling like your anger is almost out of control",
      id: 14,
    },
    {
      name: "Overwhelmed",
      pleasantness: -4,
      energy: 5,
      description: "feeling like you have been taken over by string feelings",
      id: 15,
    },
    {
      name: "Stressed",
      pleasantness: -3,
      energy: 5,
      description: "strained mentally or emotionally from many demands",
      id: 16,
    },
    {
      name: "Annoyed",
      pleasantness: -2,
      energy: 5,
      description: "bothered by something displeasing or uncomfortable",
      id: 17,
    },
    {
      name: "Pressured",
      pleasantness: -1,
      energy: 5,
      description: "feeling as if an important outcome depends on you",
      id: 18,
    },
    {
      name: "Excited",
      pleasantness: 1,
      energy: 5,
      description: "enthusiastic about something in the future",
      id: 19,
    },
    {
      name: "Determined",
      pleasantness: 2,
      energy: 5,
      description:
        "knowing what you want and not letting anything stand in the way",
      id: 20,
    },
    {
      name: "Successful",
      pleasantness: 3,
      energy: 5,
      description: "feeling lost in wonder about a particular even",
      id: 21,
    },
    {
      name: "Amazed",
      pleasantness: 4,
      energy: 5,
      description: "feeling lost in wonder about a particular event",
      id: 22,
    },
    {
      name: "Inspired",
      pleasantness: 5,
      energy: 5,
      description: "feeling like you want to do something creative",
      id: 23,
    },
    {
      name: "Empowered",
      pleasantness: 6,
      energy: 5,
      description:
        "feeling stronger or more confident due to someone or something that happened",
      id: 24,
    },
  ],
  [
    {
      name: "Furious",
      pleasantness: -6,
      energy: 4,
      description: "extremely angry about something",
      id: 25,
    },
    {
      name: "Frightened",
      pleasantness: -5,
      energy: 4,
      description: "afraid or fearful",
      id: 26,
    },
    {
      name: "Anxious",
      pleasantness: -4,
      energy: 4,
      description: "worried or uneasy about an uncertain outcome",
      id: 27,
    },
    {
      name: "Apprehensive",
      pleasantness: -3,
      energy: 4,
      description: "unease and worry about something that might happen",
      id: 28,
    },
    {
      name: "Irritated",
      pleasantness: -2,
      energy: 4,
      description: "slightly angry with or annoyed by an action or event",
      id: 29,
    },
    {
      name: "Restless",
      pleasantness: -1,
      energy: 4,
      description: "unable to relax due to anxiety or boredom",
      id: 30,
    },
    {
      name: "Energized",
      pleasantness: 1,
      energy: 4,
      description: "feeling like you are wide awake and ready to get up and go",
      id: 31,
    },
    {
      name: "Eager",
      pleasantness: 2,
      energy: 4,
      description: "impatiently wanting to do or get something",
      id: 32,
    },
    {
      name: "Enthusiastic",
      pleasantness: 3,
      energy: 4,
      description: "highly interested in an idea or activity",
      id: 33,
    },
    {
      name: "Joyful",
      pleasantness: 4,
      energy: 4,
      description: "feeling pleasure and in high spirits",
      id: 34,
    },
    {
      name: "Productive",
      pleasantness: 5,
      energy: 4,
      description:
        "feeling like you are accomplishing your tasks or achieving your goals",
      id: 35,
    },
    {
      name: "Proud",
      pleasantness: 6,
      energy: 4,
      description:
        "pleased with your own achievements or those of someone close to you",
      id: 36,
    },
  ],
  [
    {
      name: "Jealous",
      pleasantness: -6,
      energy: 3,
      description:
        "feeling threatened that you're losing an important relationship",
      id: 37,
    },
    {
      name: "Scared",
      pleasantness: -5,
      energy: 3,
      description:
        "perceiving threat or danger, whether physical or psychological",
      id: 38,
    },
    {
      name: "Angry",
      pleasantness: -4,
      energy: 3,
      description: "strongly bothered about a perceived injustice",
      id: 39,
    },
    {
      name: "Jittery",
      pleasantness: -3,
      energy: 3,
      description: "feeling on edge and jumpy",
      id: 40,
    },
    {
      name: "Fomo",
      pleasantness: -2,
      energy: 3,
      description: "fear of missing out",
      id: 41,
    },
    {
      name: "Confused",
      pleasantness: -1,
      energy: 3,
      description: "feeling unable to make sense of something",
      id: 42,
    },
    {
      name: "Cheerful",
      pleasantness: 1,
      energy: 3,
      description: "full of happy feelings",
      id: 43,
    },
    {
      name: "Curious",
      pleasantness: 2,
      energy: 3,
      description: "interested in learning something",
      id: 44,
    },
    {
      name: "Upbeat",
      pleasantness: 3,
      energy: 3,
      description: "feeling high energy and bubbly",
      id: 45,
    },
    {
      name: "Happy",
      pleasantness: 4,
      energy: 3,
      description: "very pleased and filled with joy",
      id: 46,
    },
    {
      name: "Motivated",
      pleasantness: 5,
      energy: 3,
      description: "enthusiastic about doing something",
      id: 47,
    },
    {
      name: "Optimistic",
      pleasantness: 6,
      energy: 3,
      description: "hopeful and confident about the future",
      id: 48,
    },
  ],
  [
    {
      name: "Envious",
      pleasantness: -6,
      energy: 2,
      description: "feelings of desire for something someone else has",
      id: 49,
    },
    {
      name: "Repulsed",
      pleasantness: -5,
      energy: 2,
      description: "nauseated by something or someone",
      id: 50,
    },
    {
      name: "Frustrated",
      pleasantness: -4,
      energy: 2,
      description: "upset because you cannot do something you want to do",
      id: 51,
    },
    {
      name: "Embarrassed",
      pleasantness: -3,
      energy: 2,
      description:
        "feeling self-conscious and awkward about how you think others perceive you",
      id: 52,
    },
    {
      name: "Concerned",
      pleasantness: -2,
      energy: 2,
      description: "wondering if someone or something is okay",
      id: 53,
    },
    {
      name: "Tense",
      pleasantness: -1,
      energy: 2,
      description: "unable to relax",
      id: 54,
    },
    {
      name: "Pleasant",
      pleasantness: 1,
      energy: 2,
      description: "feeling mostly positive",
      id: 55,
    },
    {
      name: "Focused",
      pleasantness: 2,
      energy: 2,
      description: "engaged in only one idea or task",
      id: 56,
    },
    {
      name: "Alive",
      pleasantness: 3,
      energy: 2,
      description: "filled with energy and vitality",
      id: 57,
    },
    {
      name: "Confident",
      pleasantness: 4,
      energy: 2,
      description: "feeling sure of yourself",
      id: 58,
    },
    {
      name: "Engaged",
      pleasantness: 5,
      energy: 2,
      description: "paying full attention or participating fully in something",
      id: 59,
    },
    {
      name: "Challenged",
      pleasantness: 6,
      energy: 2,
      description: "feeling pushed to reach a higher goal",
      id: 60,
    },
  ],
  [
    {
      name: "Contempt",
      pleasantness: -6,
      energy: 1,
      description: "feeling a combination of anger and disgust",
      id: 61,
    },
    {
      name: "Troubled",
      pleasantness: -5,
      energy: 1,
      description: "feeling worried about a problem or conflict",
      id: 62,
    },
    {
      name: "Worried",
      pleasantness: -4,
      energy: 1,
      description: "troubled about actual or potential problems",
      id: 63,
    },
    {
      name: "Nervous",
      pleasantness: -3,
      energy: 1,
      description: "jumpy and worried about the future or an uncertain event",
      id: 64,
    },
    {
      name: "Peeved",
      pleasantness: -2,
      energy: 1,
      description: "feeling left out and unwanted from a desired group",
      id: 65,
    },
    {
      name: "Uneasy",
      pleasantness: -1,
      energy: 1,
      description: "vague sense that something is wrong",
      id: 66,
    },
    {
      name: "Pleased",
      pleasantness: 1,
      energy: 1,
      description:
        "feeling content and happy about a particular situation or person",
      id: 67,
    },
    {
      name: "Playful",
      pleasantness: 2,
      energy: 1,
      description: "feeling happy and lighthearted",
      id: 68,
    },
    {
      name: "Delighted",
      pleasantness: 3,
      energy: 1,
      description: "feeling lifted by joy",
      id: 69,
    },
    {
      name: "Wishful",
      pleasantness: 4,
      energy: 1,
      description: "having or showing a wish, longing",
      id: 70,
    },
    {
      name: "Hopeful",
      pleasantness: 5,
      energy: 1,
      description: "optimistic that something good will happen",
      id: 71,
    },
    {
      name: "Accomplished",
      pleasantness: 6,
      energy: 1,
      description: "feeling effective and successful",
      id: 72,
    },
  ],
  [
    {
      name: "Disgusted",
      pleasantness: -6,
      energy: -1,
      description: "feeling a strong dislike of someone or something",
      id: 73,
    },
    {
      name: "Trapped",
      pleasantness: -5,
      energy: -1,
      description: "feeling like there's no way out",
      id: 74,
    },
    {
      name: "Insecure",
      pleasantness: -4,
      energy: -1,
      description: "feeling uncertain and unconfident about yourself",
      id: 75,
    },
    {
      name: "Disheartened",
      pleasantness: -3,
      energy: -1,
      description: "loss of resolve of determination",
      id: 76,
    },
    {
      name: "Down",
      pleasantness: -2,
      energy: -1,
      description: "feeling sad and like you have little energy",
      id: 77,
    },
    {
      name: "Bored",
      pleasantness: -1,
      energy: -1,
      description: "lacking interest in something or someone",
      id: 78,
    },
    {
      name: "Calm",
      pleasantness: 1,
      energy: -1,
      description: "feeling free of stress, agitation or worry",
      id: 79,
    },
    {
      name: "At ease",
      pleasantness: 2,
      energy: -1,
      description: "feeling relaxed and comfortable",
      id: 80,
    },
    {
      name: "Understood",
      pleasantness: 3,
      energy: -1,
      description: "feeling like someone gets you",
      id: 81,
    },
    {
      name: "Respected",
      pleasantness: 4,
      energy: -1,
      description: "feeling like people think highly of you",
      id: 82,
    },
    {
      name: "Fulfilled",
      pleasantness: 5,
      energy: -1,
      description:
        "feeling like you have accomplished important personal goals",
      id: 83,
    },
    {
      name: "Blissful",
      pleasantness: 6,
      energy: -1,
      description: "feeling full of joy",
      id: 84,
    },
  ],
  [
    {
      name: "Humiliated",
      pleasantness: -6,
      energy: -2,
      description: "feeling exposed and foolish in front of others",
      id: 85,
    },
    {
      name: "Ashamed",
      pleasantness: -5,
      energy: -2,
      description:
        "feeling lower self-worth as a result of who you are or what you did",
      id: 86,
    },
    {
      name: "Lost",
      pleasantness: -4,
      energy: -2,
      description: "feeling uncomfortably alone and lackign direction",
      id: 87,
    },
    {
      name: "Disappointed",
      pleasantness: -3,
      energy: -2,
      description: "sad beacuse your expectations were not met",
      id: 88,
    },
    {
      name: "Meh",
      pleasantness: -2,
      energy: -2,
      description: "feeling uninspired or blah",
      id: 89,
    },
    {
      name: "Tired",
      pleasantness: -1,
      energy: -2,
      description: "feeling like you need to rest",
      id: 90,
    },
    {
      name: "Good",
      pleasantness: 1,
      energy: -2,
      description: "feeling positive, like things are jsut fine",
      id: 91,
    },
    {
      name: "Thoughtful",
      pleasantness: 2,
      energy: -2,
      description: "feeling reflective and contemplative",
      id: 92,
    },
    {
      name: "Appreciated",
      pleasantness: 3,
      energy: -2,
      description: "feeling recognized and worthy",
      id: 93,
    },
    {
      name: "Supported",
      pleasantness: 4,
      energy: -2,
      description: "feeling like someone is there for you",
      id: 94,
    },
    {
      name: "Loved",
      pleasantness: 5,
      energy: -2,
      description: "feeling someone cares deeply for you",
      id: 95,
    },
    {
      name: "Connnected",
      pleasantness: 6,
      energy: -2,
      description: "feeling close to someone or part of a community",
      id: 96,
    },
  ],
  [
    {
      name: "Pessimistic",
      pleasantness: -6,
      energy: -3,
      description:
        "having a negative outlook and expecting the worst to happen",
      id: 97,
    },
    {
      name: "Vulnerable",
      pleasantness: -5,
      energy: -3,
      description:
        "feeling like you could easily be emotionally or mentally hurt",
      id: 98,
    },
    {
      name: "Disconnected",
      pleasantness: -4,
      energy: -3,
      description: "feeling separate from others",
      id: 99,
    },
    {
      name: "Forlorn",
      pleasantness: -3,
      energy: -3,
      description: "feeling both sad and alone",
      id: 100,
    },
    {
      name: "Sad",
      pleasantness: -2,
      energy: -3,
      description: "feeling unhappy about something",
      id: 101,
    },
    {
      name: "Fatigued",
      pleasantness: -1,
      energy: -3,
      description: "feeling physically drained",
      id: 102,
    },
    {
      name: "Relaxed",
      pleasantness: 1,
      energy: -3,
      description: "feeling casual and restful in body and mind",
      id: 103,
    },
    {
      name: "Chill",
      pleasantness: 2,
      energy: -3,
      description: "feeling relaxed and easygoing",
      id: 104,
    },
    {
      name: "Compassionate",
      pleasantness: 3,
      energy: -3,
      description: "showing cate and concern for someone",
      id: 105,
    },
    {
      name: "Included",
      pleasantness: 4,
      energy: -3,
      description: "feeling like you're part of a group",
      id: 106,
    },
    {
      name: "Valued",
      pleasantness: 5,
      energy: -3,
      description: "feeling like you matter",
      id: 107,
    },
    {
      name: "Grateful",
      pleasantness: 6,
      energy: -3,
      description: "appreciative of something or someone",
      id: 108,
    },
  ],
  [
    {
      name: "Guilty",
      pleasantness: -6,
      energy: -4,
      description: "feeling responsible for a specific wrongdoing",
      id: 109,
    },
    {
      name: "Numb",
      pleasantness: -5,
      energy: -4,
      description: "dampening or loss of sensitivity to feelings",
      id: 110,
    },
    {
      name: "Excluded",
      pleasantness: -4,
      energy: -4,
      description: "feeling left out and unwanted",
      id: 111,
    },
    {
      name: "Spent",
      pleasantness: -3,
      energy: -4,
      description: "feeling extremely exhausted, both in body and mind",
      id: 112,
    },
    {
      name: "Discouraged",
      pleasantness: -2,
      energy: -4,
      description: "feeling a loss of confidence and enthusiasm",
      id: 113,
    },
    {
      name: "Disengaged",
      pleasantness: -1,
      energy: -4,
      description: "feeling like you cannot focus; desinterested",
      id: 114,
    },
    {
      name: "Sympathetic",
      pleasantness: 1,
      energy: -4,
      description: "feeling sorry or sorrowful for someone else",
      id: 115,
    },
    {
      name: "Comfortable",
      pleasantness: 2,
      energy: -4,
      description: "feeling reassured both in mind and body",
      id: 116,
    },
    {
      name: "Empathetic",
      pleasantness: 3,
      energy: -4,
      description:
        "understanding and temporarily sharing the feelings of someone else",
      id: 117,
    },
    {
      name: "Content",
      pleasantness: 4,
      energy: -4,
      description: "feeling complete and like you are enough",
      id: 118,
    },
    {
      name: "Accepted",
      pleasantness: 5,
      energy: -4,
      description: "feeling acknowledged and seen",
      id: 119,
    },
    {
      name: "Moved",
      pleasantness: 6,
      energy: -4,
      description:
        "a sudden feeling that happens after seeing something inspirational or sad",
      id: 120,
    },
  ],
  [
    {
      name: "Depressed",
      pleasantness: -6,
      energy: -5,
      description: "extremely unhappy and dispirited",
      id: 121,
    },
    {
      name: "Hopeless",
      pleasantness: -5,
      energy: -5,
      description: "feel completely defeated and in despair about the future",
      id: 122,
    },
    {
      name: "Alienated",
      pleasantness: -4,
      energy: -5,
      description: "feeling like you have been made a stranger to others",
      id: 123,
    },
    {
      name: "Nostalgic",
      pleasantness: -3,
      energy: -5,
      description:
        "a sentimental longing for the happiness left in former place, time or situtation",
      id: 124,
    },
    {
      name: "Lonely",
      pleasantness: -2,
      energy: -5,
      description: "feeling sad because you are alone or disconncted",
      id: 125,
    },
    {
      name: "Apathetic",
      pleasantness: -1,
      energy: -5,
      description: "lacking enthusiasm or interest",
      id: 126,
    },
    {
      name: "Mellow",
      pleasantness: 1,
      energy: -5,
      description: "relaxed and laid back",
      id: 127,
    },
    {
      name: "Peaceful",
      pleasantness: 2,
      energy: -5,
      description: "quiet and calm",
      id: 128,
    },
    {
      name: "Balanced",
      pleasantness: 3,
      energy: -5,
      description: "feeling stable and satisfied",
      id: 129,
    },
    {
      name: "Safe",
      pleasantness: 4,
      energy: -5,
      description: "feeling protected from danger",
      id: 130,
    },
    {
      name: "Secure",
      pleasantness: 5,
      energy: -5,
      description: "feeling safe and protected",
      id: 131,
    },
    {
      name: "Blessed",
      pleasantness: 6,
      energy: -5,
      description: "feeling thankful and fortunate for what you have",
      id: 132,
    },
  ],
  [
    {
      name: "Miserable",
      pleasantness: -6,
      energy: -6,
      description: "feeling absolutely awful",
      id: 133,
    },
    {
      name: "Despair",
      pleasantness: -5,
      energy: -6,
      description: "a feeling of complete hopelessness",
      id: 134,
    },
    {
      name: "Glum",
      pleasantness: -4,
      energy: -6,
      description: "feeling displeased",
      id: 135,
    },
    {
      name: "Burned out",
      pleasantness: -3,
      energy: -6,
      description: "feeling exhausted from ongoing stress",
      id: 136,
    },
    {
      name: "Exhausted",
      pleasantness: -2,
      energy: -6,
      description: "feeling depleted of all energy",
      id: 137,
    },
    {
      name: "Helpless",
      pleasantness: -1,
      energy: -6,
      description: "feeling like there's nothing you can do",
      id: 138,
    },
    {
      name: "Carefree",
      pleasantness: 1,
      energy: -6,
      description: "feeling free of worry and lighthearted",
      id: 139,
    },
    {
      name: "Tranquil",
      pleasantness: 2,
      energy: -6,
      description: "peaceful, free from tension",
      id: 140,
    },
    {
      name: "Thankful",
      pleasantness: 3,
      energy: -6,
      description: "feeling pleased or appreciative",
      id: 141,
    },
    {
      name: "Relieved",
      pleasantness: 4,
      energy: -6,
      description: "feeling at ease after an unpleasant feeling goes away",
      id: 142,
    },
    {
      name: "Satisfied",
      pleasantness: 5,
      energy: -6,
      description: "pleased with what you have or with something you did",
      id: 143,
    },
    {
      name: "Serene",
      pleasantness: 6,
      energy: -6,
      description: "calm and peaceful",
      id: 144,
    },
  ],
];
