import { Emotion } from "@/types";

export const rulerEmotionsMatrix: Emotion[][] = [
  [
    {
      name: "Enraged",
      pleasantness: -6,
      energy: 6,
      description: "made furious by something; filled with extreme anger",
    },
    {
      name: "Terrified",
      pleasantness: -5,
      energy: 6,
      description: "consumed by fear",
    },
    {
      name: "Panicked",
      pleasantness: -4,
      energy: 6,
      description: "feeling frantic and overcome by fear",
    },
    {
      name: "Shocked",
      pleasantness: -3,
      energy: 6,
      description: "experiencing extreme horrir, disgust, and surprise",
    },
    {
      name: "Impassioned",
      pleasantness: -2,
      energy: 6,
      description: "filled with lots of emotion",
    },
    {
      name: "Hyper",
      pleasantness: -1,
      energy: 6,
      description: "feeling energetic and like you want to move around",
    },
    {
      name: "Surprised",
      pleasantness: 1,
      energy: 6,
      description: "caught off guard by something unexpected or unusual",
    },
    {
      name: "Awe",
      pleasantness: 2,
      energy: 6,
      description: "feeling like you are in presence of something vast",
    },
    {
      name: "Exhilirated",
      pleasantness: 3,
      energy: 6,
      description: "in high spirits; cheerful and envigorated",
    },
    {
      name: "Thrilled",
      pleasantness: 4,
      energy: 6,
      description: "feeling very excited all of a sudden",
    },
    {
      name: "Elated",
      pleasantness: 5,
      energy: 6,
      description: "very joyful, proud, or enthusiastic",
    },
    {
      name: "Ecstatic",
      pleasantness: 6,
      energy: 6,
      description: "feeling intense joy or happiness",
    },
  ],
  [
    {
      name: "Livid",
      pleasantness: -6,
      energy: 5,
      description: "feeling furious about something or someone",
    },
    {
      name: "Irate",
      pleasantness: -5,
      energy: 5,
      description: "feeling like your anger is almost out of control",
    },
    {
      name: "Overwhelmed",
      pleasantness: -4,
      energy: 5,
      description: "feeling like you have been taken over by string feelings",
    },
    {
      name: "Stressed",
      pleasantness: -3,
      energy: 5,
      description: "strained mentally or emotionally from many demands",
    },
    {
      name: "Annoyed",
      pleasantness: -2,
      energy: 5,
      description: "bothered by something displeasing or uncomfortable",
    },
    {
      name: "Pressured",
      pleasantness: -1,
      energy: 5,
      description: "feeling as if an important outcome depends on you",
    },
    {
      name: "Excited",
      pleasantness: 1,
      energy: 5,
      description: "enthusiastic about something in the future",
    },
    {
      name: "Determined",
      pleasantness: 2,
      energy: 5,
      description:
        "knowing what you want and not letting anything stand in the way",
    },
    {
      name: "Successful",
      pleasantness: 3,
      energy: 5,
      description: "feeling lost in wonder about a particular even",
    },
    {
      name: "Amazed",
      pleasantness: 4,
      energy: 5,
      description: "feeling lost in wonder about a particular event",
    },
    {
      name: "Inspired",
      pleasantness: 5,
      energy: 5,
      description: "feeling like you want to do something creative",
    },
    {
      name: "Empowered",
      pleasantness: 6,
      energy: 5,
      description:
        "feeling stronger or more confident due to someone or something that happened",
    },
  ],
  [
    {
      name: "Furious",
      pleasantness: -6,
      energy: 4,
      description: "extremely angry about something",
    },
    {
      name: "Frightened",
      pleasantness: -5,
      energy: 4,
      description: "afraid or fearful",
    },
    {
      name: "Anxious",
      pleasantness: -4,
      energy: 4,
      description: "worried or uneasy about an uncertain outcome",
    },
    {
      name: "Apprehensive",
      pleasantness: -3,
      energy: 4,
      description: "unease and worry about something that might happen",
    },
    {
      name: "Irritated",
      pleasantness: -2,
      energy: 4,
      description: "slightly angry with or annoyed by an action or event",
    },
    {
      name: "Restless",
      pleasantness: -1,
      energy: 4,
      description: "unable to relax due to anxiety or boredom",
    },
    {
      name: "Energized",
      pleasantness: 1,
      energy: 4,
      description: "feeling like you are wide awake and ready to get up and go",
    },
    {
      name: "Eager",
      pleasantness: 2,
      energy: 4,
      description: "impatiently wanting to do or get something",
    },
    {
      name: "Enthusiastic",
      pleasantness: 3,
      energy: 4,
      description: "highly interested in an idea or activity",
    },
    {
      name: "Joyful",
      pleasantness: 4,
      energy: 4,
      description: "feeling pleasure and in high spirits",
    },
    {
      name: "Productive",
      pleasantness: 5,
      energy: 4,
      description:
        "feeling like you are accomplishing your tasks or achieving your goals",
    },
    {
      name: "Proud",
      pleasantness: 6,
      energy: 4,
      description:
        "pleased with your own achievements or those of someone close to you",
    },
  ],
  [
    {
      name: "Jealous",
      pleasantness: -6,
      energy: 3,
      description:
        "feeling threatened that you're losing an important relationship",
    },
    {
      name: "Scared",
      pleasantness: -5,
      energy: 3,
      description:
        "perceiving threat or danger, whether physical or psychological",
    },
    {
      name: "Angry",
      pleasantness: -4,
      energy: 3,
      description: "strongly bothered about a perceived injustice",
    },
    {
      name: "Jittery",
      pleasantness: -3,
      energy: 3,
      description: "feeling on edge and jumpy",
    },
    {
      name: "Fomo",
      pleasantness: -2,
      energy: 3,
      description: "fear of missing out",
    },
    {
      name: "Confused",
      pleasantness: -1,
      energy: 3,
      description: "feeling unable to make sense of something",
    },
    {
      name: "Cheerful",
      pleasantness: 1,
      energy: 3,
      description: "full of happy feelings",
    },
    {
      name: "Curious",
      pleasantness: 2,
      energy: 3,
      description: "interested in learning something",
    },
    {
      name: "Upbeat",
      pleasantness: 3,
      energy: 3,
      description: "feeling high energy and bubbly",
    },
    {
      name: "Happy",
      pleasantness: 4,
      energy: 3,
      description: "very pleased and filled with joy",
    },
    {
      name: "Motivated",
      pleasantness: 5,
      energy: 3,
      description: "enthusiastic about doing something",
    },
    {
      name: "Optimistic",
      pleasantness: 6,
      energy: 3,
      description: "hopeful and confident about the future",
    },
  ],
  [
    {
      name: "Envious",
      pleasantness: -6,
      energy: 2,
      description: "feelings of desire for something someone else has",
    },
    {
      name: "Repulsed",
      pleasantness: -5,
      energy: 2,
      description: "nauseated by something or someone",
    },
    {
      name: "Frustrated",
      pleasantness: -4,
      energy: 2,
      description: "upset because you cannot do something you want to do",
    },
    {
      name: "Embarrassed",
      pleasantness: -3,
      energy: 2,
      description:
        "feeling self-conscious and awkward about how you think others perceive you",
    },
    {
      name: "Concerned",
      pleasantness: -2,
      energy: 2,
      description: "wondering if someone or something is okay",
    },
    {
      name: "Tense",
      pleasantness: -1,
      energy: 2,
      description: "unable to relax",
    },
    {
      name: "Pleasant",
      pleasantness: 1,
      energy: 2,
      description: "feeling mostly positive",
    },
    {
      name: "Focused",
      pleasantness: 2,
      energy: 2,
      description: "engaged in only one idea or task",
    },
    {
      name: "Alive",
      pleasantness: 3,
      energy: 2,
      description: "filled with energy and vitality",
    },
    {
      name: "Confident",
      pleasantness: 4,
      energy: 2,
      description: "feeling sure of yourself",
    },
    {
      name: "Engaged",
      pleasantness: 5,
      energy: 2,
      description: "paying full attention or participating fully in something",
    },
    {
      name: "Challenged",
      pleasantness: 6,
      energy: 2,
      description: "feeling pushed to reach a higher goal",
    },
  ],
  [
    {
      name: "Contempt",
      pleasantness: -6,
      energy: 1,
      description: "feeling a combination of anger and disgust",
    },
    {
      name: "Troubled",
      pleasantness: -5,
      energy: 1,
      description: "feeling worried about a problem or conflict",
    },
    {
      name: "Worried",
      pleasantness: -4,
      energy: 1,
      description: "troubled about actual or potential problems",
    },
    {
      name: "Nervous",
      pleasantness: -3,
      energy: 1,
      description: "jumpy and worried about the future or an uncertain event",
    },
    {
      name: "Peeved",
      pleasantness: -2,
      energy: 1,
      description: "feeling left out and unwanted from a desired group",
    },
    {
      name: "Uneasy",
      pleasantness: -1,
      energy: 1,
      description: "vague sense that something is wrong",
    },
    {
      name: "Pleased",
      pleasantness: 1,
      energy: 1,
      description:
        "feeling content and happy about a particular situation or person",
    },
    {
      name: "Playful",
      pleasantness: 2,
      energy: 1,
      description: "feeling happy and lighthearted",
    },
    {
      name: "Delighted",
      pleasantness: 3,
      energy: 1,
      description: "feeling lifted by joy",
    },
    {
      name: "Wishful",
      pleasantness: 4,
      energy: 1,
      description: "having or showing a wish, longing",
    },
    {
      name: "Hopeful",
      pleasantness: 5,
      energy: 1,
      description: "optimistic that something good will happen",
    },
    {
      name: "Accomplished",
      pleasantness: 6,
      energy: 1,
      description: "feeling effective and successful",
    },
  ],
  [
    {
      name: "Disgusted",
      pleasantness: -6,
      energy: -1,
      description: "feeling a strong dislike of someone or something",
    },
    {
      name: "Trapped",
      pleasantness: -5,
      energy: -1,
      description: "feeling like there's no way out",
    },
    {
      name: "Insecure",
      pleasantness: -4,
      energy: -1,
      description: "feeling uncertain and unconfident about yourself",
    },
    {
      name: "Disheartened",
      pleasantness: -3,
      energy: -1,
      description: "loss of resolve of determination",
    },
    {
      name: "Down",
      pleasantness: -2,
      energy: -1,
      description: "feeling sad and like you have little energy",
    },
    {
      name: "Bored",
      pleasantness: -1,
      energy: -1,
      description: "lacking interest in something or someone",
    },
    {
      name: "Calm",
      pleasantness: 1,
      energy: -1,
      description: "feeling free of stress, agitation or worry",
    },
    {
      name: "At ease",
      pleasantness: 2,
      energy: -1,
      description: "feeling relaxed and comfortable",
    },
    {
      name: "Understood",
      pleasantness: 3,
      energy: -1,
      description: "feeling like someone gets you",
    },
    {
      name: "Respected",
      pleasantness: 4,
      energy: -1,
      description: "feeling like people think highly of you",
    },
    {
      name: "Fulfilled",
      pleasantness: 5,
      energy: -1,
      description:
        "feeling like you have accomplished important personal goals",
    },
    {
      name: "Blissful",
      pleasantness: 6,
      energy: -1,
      description: "feeling full of joy",
    },
  ],
  [
    {
      name: "Humiliated",
      pleasantness: -6,
      energy: -2,
      description: "feeling exposed and foolish in front of others",
    },
    {
      name: "Ashamed",
      pleasantness: -5,
      energy: -2,
      description:
        "feeling lower self-worth as a result of who you are or what you did",
    },
    {
      name: "Lost",
      pleasantness: -4,
      energy: -2,
      description: "feeling uncomfortably alone and lackign direction",
    },
    {
      name: "Disappointed",
      pleasantness: -3,
      energy: -2,
      description: "sad beacuse your expectations were not met",
    },
    {
      name: "Meh",
      pleasantness: -2,
      energy: -2,
      description: "feeling uninspired or blah",
    },
    {
      name: "Tired",
      pleasantness: -1,
      energy: -2,
      description: "feeling like you need to rest",
    },
    {
      name: "Good",
      pleasantness: 1,
      energy: -2,
      description: "feeling positive, like things are jsut fine",
    },
    {
      name: "Thoughtful",
      pleasantness: 2,
      energy: -2,
      description: "feeling reflective and contemplative",
    },
    {
      name: "Appreciated",
      pleasantness: 3,
      energy: -2,
      description: "feeling recognized and worthy",
    },
    {
      name: "Supported",
      pleasantness: 4,
      energy: -2,
      description: "feeling like someone is there for you",
    },
    {
      name: "Loved",
      pleasantness: 5,
      energy: -2,
      description: "feeling someone cares deeply for you",
    },
    {
      name: "Connnected",
      pleasantness: 6,
      energy: -2,
      description: "feeling close to someone or part of a community",
    },
  ],
  [
    {
      name: "Pessimistic",
      pleasantness: -6,
      energy: -3,
      description:
        "having a negative outlook and expecting the worst to happen",
    },
    {
      name: "Vulnerable",
      pleasantness: -5,
      energy: -3,
      description:
        "feeling like you could easily be emotionally or mentally hurt",
    },
    {
      name: "Disconnected",
      pleasantness: -4,
      energy: -3,
      description: "feeling separate from others",
    },
    {
      name: "Forlorn",
      pleasantness: -3,
      energy: -3,
      description: "feeling both sad and alone",
    },
    {
      name: "Sad",
      pleasantness: -2,
      energy: -3,
      description: "feeling unhappy about something",
    },
    {
      name: "Fatigued",
      pleasantness: -1,
      energy: -3,
      description: "feeling physically drained",
    },
    {
      name: "Relaxed",
      pleasantness: 1,
      energy: -3,
      description: "feeling casual and restful in body and mind",
    },
    {
      name: "Chill",
      pleasantness: 2,
      energy: -3,
      description: "feeling relaxed and easygoing",
    },
    {
      name: "Compassionate",
      pleasantness: 3,
      energy: -3,
      description: "showing cate and concern for someone",
    },
    {
      name: "Included",
      pleasantness: 4,
      energy: -3,
      description: "feeling like you're part of a group",
    },
    {
      name: "Valued",
      pleasantness: 5,
      energy: -3,
      description: "feeling like you matter",
    },
    {
      name: "Grateful",
      pleasantness: 6,
      energy: -3,
      description: "appreciative of something or someone",
    },
  ],
  [
    {
      name: "Guilty",
      pleasantness: -6,
      energy: -4,
      description: "feeling responsible for a specific wrongdoing",
    },
    {
      name: "Numb",
      pleasantness: -5,
      energy: -4,
      description: "dampening or loss of sensitivity to feelings",
    },
    {
      name: "Excluded",
      pleasantness: -4,
      energy: -4,
      description: "feeling left out and unwanted",
    },
    {
      name: "Spent",
      pleasantness: -3,
      energy: -4,
      description: "feeling extremely exhausted, both in body and mind",
    },
    {
      name: "Discouraged",
      pleasantness: -2,
      energy: -4,
      description: "feeling a loss of confidence and enthusiasm",
    },
    {
      name: "Disengaged",
      pleasantness: -1,
      energy: -4,
      description: "feeling like you cannot focus; desinterested",
    },
    {
      name: "Sympathetic",
      pleasantness: 1,
      energy: -4,
      description: "feeling sorry or sorrowful for someone else",
    },
    {
      name: "Comfortable",
      pleasantness: 2,
      energy: -4,
      description: "feeling reassured both in mind and body",
    },
    {
      name: "Empathetic",
      pleasantness: 3,
      energy: -4,
      description:
        "understanding and temporarily sharing the feelings of someone else",
    },
    {
      name: "Content",
      pleasantness: 4,
      energy: -4,
      description: "feeling complete and like you are enough",
    },
    {
      name: "Accepted",
      pleasantness: 5,
      energy: -4,
      description: "feeling acknowledged and seen",
    },
    {
      name: "Moved",
      pleasantness: 6,
      energy: -4,
      description:
        "a sudden feeling that happens after seeing something inspirational or sad",
    },
  ],
  [
    {
      name: "Depressed",
      pleasantness: -6,
      energy: -5,
      description: "extremely unhappy and dispirited",
    },
    {
      name: "Hopeless",
      pleasantness: -5,
      energy: -5,
      description: "feel completely defeated and in despair about the future",
    },
    {
      name: "Alienated",
      pleasantness: -4,
      energy: -5,
      description: "feeling like you have been made a stranger to others",
    },
    {
      name: "Nostalgic",
      pleasantness: -3,
      energy: -5,
      description:
        "a sentimental longing for the happiness left in former place, time or situtation",
    },
    {
      name: "Lonely",
      pleasantness: -2,
      energy: -5,
      description: "feeling sad because you are alone or disconncted",
    },
    {
      name: "Apathetic",
      pleasantness: -1,
      energy: -5,
      description: "lacking enthusiasm or interest",
    },
    {
      name: "Mellow",
      pleasantness: 1,
      energy: -5,
      description: "relaxed and laid back",
    },
    {
      name: "Peaceful",
      pleasantness: 2,
      energy: -5,
      description: "quiet and calm",
    },
    {
      name: "Balanced",
      pleasantness: 3,
      energy: -5,
      description: "feeling stable and satisfied",
    },
    {
      name: "Safe",
      pleasantness: 4,
      energy: -5,
      description: "feeling protected from danger",
    },
    {
      name: "Secure",
      pleasantness: 5,
      energy: -5,
      description: "feeling safe and protected",
    },
    {
      name: "Blessed",
      pleasantness: 6,
      energy: -5,
      description: "feeling thankful and fortunate for what you have",
    },
  ],
  [
    {
      name: "Miserable",
      pleasantness: -6,
      energy: -6,
      description: "feeling absolutely awful",
    },
    {
      name: "Despair",
      pleasantness: -5,
      energy: -6,
      description: "a feeling of complete hopelessness",
    },
    {
      name: "Glum",
      pleasantness: -4,
      energy: -6,
      description: "feeling displeased",
    },
    {
      name: "Burned out",
      pleasantness: -3,
      energy: -6,
      description: "feeling exhausted from ongoing stress",
    },
    {
      name: "Exhausted",
      pleasantness: -2,
      energy: -6,
      description: "feeling depleted of all energy",
    },
    {
      name: "Helpless",
      pleasantness: -1,
      energy: -6,
      description: "feeling like there's nothing you can do",
    },
    {
      name: "Carefree",
      pleasantness: 1,
      energy: -6,
      description: "feeling free of worry and lighthearted",
    },
    {
      name: "Tranquil",
      pleasantness: 2,
      energy: -6,
      description: "peaceful, free from tension",
    },
    {
      name: "Thankful",
      pleasantness: 3,
      energy: -6,
      description: "feeling pleased or appreciative",
    },
    {
      name: "Relieved",
      pleasantness: 4,
      energy: -6,
      description: "feeling at ease after an unpleasant feeling goes away",
    },
    {
      name: "Satisfied",
      pleasantness: 5,
      energy: -6,
      description: "pleased with what you have or with something you did",
    },
    {
      name: "Serene",
      pleasantness: 6,
      energy: -6,
      description: "calm and peaceful",
    },
  ],
];
