import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Feedback Flow",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"h-dvh w-dvw overflow-hidden"}>{children}</body>
    </html>
  );
}
