import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Feedback Flow",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className={"h-dvh w-dvw overflow-hidden"}>{children}</main>;
}
