name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
  POSTGRES_URL: ${{ secrets.POSTGRES_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Install SST
        run: |
          wget https://github.com/sst/ion/releases/download/v0.0.384/sst-linux-amd64.deb 
          sudo dpkg -i sst-linux-amd64.deb

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 1200
          aws-region: us-east-1

      - name: Unlock SST
        run: |
          sst unlock --stage prod

      - name: Deploy to AWS with SST
        run: |
          bun install
          sst deploy --stage=prod --verbose
